export type EaCustomer = {
  email: string | null;
  last_name: string | null;
  fork_no: number | null;
  fon: string | null;
  first_name: string | null;
  city: string | null;
  fax: string | null;
  customer_no: number | null;
  weight: string | null;
  user_group: string | null;
  customerclient_no: string | null;
  height: string | null;
  uid_customer: number;
  created_at: Date | null;
  updated_at: Date | null;
  region: string | null;
  mobile: string | null;
  cal_address: string | null;
  customer_no_rel: string | null;
  order_no: number | null;
  check_export_ups: number | null;
  company: string | null;
  no_vat: number | null;
  bank_account: string | null;
  bank_payment: string | null;
  vat_no: string | null;
  customer_category_no: number | null;
  delivery_address: string | null;
};
