export enum ValueTypes {
  ea_articles_category = "ea_articles_category",
  ea_compr_in = "ea_compr_in",
  ea_compr_out = "ea_compr_out",
  ea_customer_payment = "ea_customer_payment",
  ea_forks_category = "ea_forks_category",
  ea_forks_color = "ea_forks_color",
  ea_forks_settings = "ea_forks_settings",
  ea_forks_use = "ea_forks_use",
  ea_rebound_in = "ea_rebound_in",
  ea_rebound_out = "ea_rebound_out",
  ea_ref_forks_parts = "ea_ref_forks_parts",
  ea_value_air = "ea_value_air",
  ea_value_ap = "ea_value_ap",
  ea_value_car = "ea_value_car",
  ea_value_cs = "ea_value_cs",
  ea_value_di = "ea_value_di",
  ea_value_hs = "ea_value_hs",
  ea_value_ns = "ea_value_ns",
  ea_value_ov = "ea_value_ov",
  ea_value_sb = "ea_value_sb",
  ea_value_tax = "ea_value_tax",
  ea_value_ts = "ea_value_ts",
  ea_value_ws = "ea_value_ws",
  ea_empty = "",
}
