import z from "zod";

export const worksheetSchema = z.object({
  uid_worksheet: z.number().int(),
  ap_airpreasure: z.string().nullable(),
  calc_or1: z.number(),
  calc_or2: z.number(),
  calc_or3: z.number(),
  calc_or4: z.number(),
  calc_nl13: z.number(),
  calc_nl24: z.number(),
  calc_si13: z.number(),
  calc_si24: z.number(),
  calc_so13: z.number(),
  calc_so24: z.number(),
  cart_comp_measure_1: z.string().nullable(),
  cart_comp_measure_2: z.string().nullable(),
  cart_comp_measure_3: z.string().nullable(),
  cart_comp_measure_4: z.string().nullable(),
  cart_comp_ship_1: z.string().nullable(),
  cart_comp_ship_2: z.string().nullable(),
  cart_comp_ship_3: z.string().nullable(),
  cart_comp_ship_4: z.string().nullable(),
  cart_reb_measure_1: z.string().nullable(),
  cart_reb_measure_2: z.string().nullable(),
  cart_reb_measure_3: z.string().nullable(),
  cart_reb_measure_4: z.string().nullable(),
  cart_reb_ship_1: z.string().nullable(),
  cart_reb_ship_2: z.string().nullable(),
  cart_reb_ship_3: z.string().nullable(),
  cart_reb_ship_4: z.string().nullable(),
  cs_coilspring: z.string().nullable(),
  innerraces_1_in: z.number(),
  innerraces_1_out: z.number(),
  innerraces_2_in: z.number(),
  innerraces_2_out: z.number(),
  innerraces_3_in: z.number(),
  innerraces_3_out: z.number(),
  innerraces_4_in: z.number(),
  innerraces_4_out: z.number(),
  ns_negspring: z.string().nullable(),
  outerraces_1_out: z.number(),
  outerraces_2_out: z.number(),
  outerraces_3_out: z.number(),
  outerraces_4_out: z.number(),
  ov_oilviscosity: z.string().nullable(),
  steeringinner_si13_1: z.number(),
  steeringinner_si13_2: z.number(),
  steeringinner_si13_3: z.number(),
  steeringinner_si24_1: z.number(),
  steeringinner_si24_2: z.number(),
  steeringinner_si24_3: z.number(),
  steeringouter_so13_1: z.number(),
  steeringouter_so13_2: z.number(),
  steeringouter_so13_3: z.number(),
  steeringouter_so24_1: z.number(),
  steeringouter_so24_2: z.number(),
  steeringouter_so24_3: z.number(),
  text_consult_worksheet: z.string().nullable(),

  worker_worksheet: z.string().nullable(),
  work_worksheet_date: z.union([z.string(), z.date()]).nullable(),
  worksheet_date: z.union([z.string(), z.date()]).nullable(),
  worksheet_no: z.number().int().nullable(),
  outerraces_1_in: z.number(),
  outerraces_2_in: z.number(),
  outerraces_3_in: z.number(),
  outerraces_4_in: z.number(),
  user_group: z.string().nullable(),
  uid_order: z.number().int(),

  notes_worksheet_extern: z.string().nullable(),
  notes_intern_worksheet: z.string().nullable(),
});

export type WorksheetForm = z.infer<typeof worksheetSchema>;
