export type EaOrdersOverview = {
  uid_order: number;
  invoice_date: string | null;
  order_no: number | null;
  customer_no: number | null;
  customer_name: string | null;
  customer_client_name: string | null;
  fork_no: number | null;
  fork_model: string | null;
  created_at: string | null;
  order_status: string | null;
  warranty_no: number | null;
  invoice_no: number | null;
  number: string | null;
  user_group: string | null;
  warranty_request: string | null;
  customer_address: string | null;
  worksheet_no: number | null;
  diagnosis_no: number | null;
  fork_in_date: string | null;
  costestimates_numbers: string | null;
  ftsearch: string | null;
};
