export interface EaOrder {
  uid_order: number;
  bank_account: string | null;
  bank_id: string;
  bank_name: string | null;
  bank_payment: string | null;
  cal_amount_price_categ3: number;
  cal_outstanding_money: number;
  check_extras: string;
  customer_address: string | null;
  customer_address_alt: string | null;
  costestimates_numbers?: any;
  customer_category_no: number | null;
  customer_client_height: string;
  customer_client_name: string;
  customer_client_weight: string;
  customer_email: string | null;
  customer_fon: string | null;
  customer_name: string;
  customer_no: number | null;
  date_modifikation?: any;
  dealers_client_form: number;
  fork_color: string;
  fork_freight_forwarder: string;
  fork_freight_no: string;
  fork_in_carrier: string | null;
  fork_in_date: string;
  fork_invoice_no?: any;
  fork_model: string;
  fork_no: number;
  fork_pickup_time: string;
  fork_shipped_date: string;
  invoice_date: string;
  invoice_no: number;
  notes_costestimate_extern: string;
  notes_intern: string;
  notes_invoice_extern: string;
  order_modifikation?: any;
  order_no: number;
  order_status: string;
  price_categ1_subtotal: number;
  price_categ1_total: number;
  price_categ1_valuetax: number;
  price_categ2_subtotal: number;
  price_categ2_total: number;
  price_categ2_valuetax: number;
  price_categ3_freight_subtotal: number;
  price_categ3_labor_subtotal: number;
  price_categ3_material_subtotal: number;
  price_categ3_subtotal: number;
  price_categ3_total: number;
  price_categ3_valuetax: number;
  price_outstanding_money: number;
  price_payments_total: number;
  number: string;
  printstatus_articlesales?: any;
  printstatus_costestimate?: any;
  printstatus_invoice?: any;
  reason_air: number;
  reason_oil: number;
  reason_other: number;
  reason_telescope: number;
  reminder_date: string;
  reminder_level: number;
  sold_units_reserved: number;
  text_payments: string;
  user_print_language: string;
  value_tax: number;
  vat_no_customer: string | null;
  worker_invoice: string;
  worker_invoice_no: number;
  user_group: string;
  uid_ref_fork: number;
  uid_customer: number | null;
  uid_client: number;
  uid_fork: number;
  created_at: string;
  updated_at: string;
  wheelsize: string;
  value_tax2: number;
  no_vat: number | null;
  ea_orderscol?: any;
  ftsearch: string;
  diagnosis_no?: number;
  worksheet_no?: number;
}
