export type EaDiagnosis = {
  uid_diagnosis: number;
  worker_diagnosis_no: number | null;
  check_air: string | null;
  check_cartridge: string | null;
  check_dial: string | null;
  check_headset: string | null;
  check_shockboot: string | null;
  check_telescope: string | null;
  customer_height: string | null;
  customer_weight: string | null;
  diagnosis_no: number | null;
  fork_invoice_date: string | null;
  fork_setting: string | null;
  fork_use: string | null;
  notes_diagnosis_extern: string | null;
  notes_intern: string | null;
  notes_warranty_extern: string | null;
  printstatus_diagnosis: string | null;
  warranty_request: string | null;
  work_diagnosis_time_end: string | null;
  work_diagnosis_time_start: string | null;
  worker_diagnosis: string | null;
  work_diagnosis_date: string | null;
  user_group: string | null;
  uid_order: number;
  created_at: string | null;
  updated_at: string | null;
  diagnosis_date: string | null;
  check_extras: string | null;
};
