export type EaWarranty = {
  uid_warranty: number;
  article_warranty_int: number | null;
  cal_warranty_request_find_int: number | null;
  printstatus_warranty: string | null;
  text_consult_warranty: string | null;
  wa_comments: string | null;
  wa_failure_primary: string | null;
  wa_failure_secondary: string | null;
  wa_fork_model: string | null;
  wa_id_cartridge: string | null;
  wa_mfg_day: number | null;
  wa_mfg_month: number | null;
  wa_mfg_year: number | null;
  warranty_date: string | null;
  warranty_invoice_date: string | null;
  warranty_invoice_no: number | null;
  warranty_no: number | null;
  warranty_reason: string | null;
  warranty_reason_text_no: number | null;
  work_warranty_date: string | null;
  work_warranty_time_end: string | null;
  work_warranty_time_start: string | null;
  worker_warranty: string | null;
  worker_warranty_no: number | null;
  user_group: string | null;
  uid_order: number;
  created_at: string | null;
  updated_at: string | null;
  warranty_request: string | null;
  google_doc: number | null;
};
