export type EaOrdersPositions = {
  uid_orders_position: number;
  article_creditnote_int: number | null;
  articlecharacter: string | null;
  cal_value_tax: number;
  fork_no_rel: string | null;
  currency: string | null;
  order_no: number | null;
  article_warranty_int: number | null;
  amount_price_categ3_labor: number;
  cal_price: number;
  price_single_categ2: number;
  amount_price_categ1: number;
  customer_category_no: number | null;
  amount_price_categ3_freight: number;
  user_print_language: string | null;
  article_group: string | null;
  price_single_categ3: number;
  articlediscription: string | null;
  amount_price_categ3_material: number;
  article_no_rel: string | null;
  cal_price_categ3: number;
  customer_no: number | null;
  cal_price_categ2: number;
  articlecode: string | null;
  cal_price_categ1: number;
  article_no: number | null;
  customer_no_rel: string | null;
  fork_no: number | null;
  user_group: string | null;
  order_no_rel: string | null;
  amount_price_categ2: number;
  price_single_categ1: number;
  amount_price_categ3: number;
  quantity: number;
  units: number;
  uid_article: number;
  uid_customer: number;
  uid_ref_fork: number;
  uid_order: number;
  created_at: string | null;
  updated_at: string | null;
  uid_costestimates: number | null;
  cal_value_tax2: number | null;
};
